
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-support-path
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /middleware
        pathType: Prefix
        backend:
          service:
            name: middleware
            port:
              number: 8080  
      - path: /mobility
        pathType: Prefix
        backend:
          service:
            name: mobility
            port:
              number: 8081