apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  namespace: ingress-basic
  labels:
    app: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: project231.azurecr.io/services/springboot-app:latest
        env:
        - name: api_env
          value: #{api_env}#
        - name: RDS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: dbdetails
              key: RDS_HOSTNAME
        - name: RDS_PORT
          valueFrom:
            secretKeyRef:
              name: dbdetails
              key: RDS_PORT
        - name: RDS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: dbdetails
              key: RDS_DB_NAME
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: dbdetails
              key: RDS_USERNAME
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbdetails
              key: RDS_PASSWORD
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret