apiVersion: v1
kind: Secret
metadata:
  name: dbdetails
  namespace: ingress-basic
type: Opaque
stringData:
    RDS_HOSTNAME: "prjct-db.mysql.database.azure.com"
    RDS_PORT: "3306"
    RDS_DB_NAME: "todos"
    RDS_USERNAME: "zpadmin"
    RDS_PASSWORD: "Jet123!@"